### ISSUE TITLE
read_fwf and pipe connections

### ISSUE THREAD

**Issue by r2evans** [tidyverse/readr#1003]
Similar to #552, a `pipe(...)` connection is not recognized in `read_fwf`:

```r
read_fwf(system("c:/Rtools/bin/echo -e 'a b\nc d'", intern = TRUE),
         fwf_widths(c(2, 1)))
# # A tibble: 2 x 2
#   X1    X2   
#   <chr> <chr>
# 1 a     b    
# 2 c     d    
read_fwf(pipe("c:/Rtools/bin/echo -e 'a b\nc d'"),
         fwf_widths(c(2, 1)))
# Error in isOpen(con) : invalid connection
```

On linux:

```r
readLines(pipe("/bin/echo -e 'a b\nc d'"))
# [1] "a b" "c d"

readr::read_fwf(pipe("/bin/echo -e 'a b\nc d'"), readr::fwf_widths(c(2,1)))
# Error in isOpen(con) : invalid connection
```

`readr-1.3.1` on both systems.

**Comment by BEFH** [comment]
I am still having this issue

**Comment by jimhester** [comment]
Unfortunately due to the design of readr supporting this is challenging, `read_fwf()` needs to read the file multiple times, which obviously is incompatible with pipe connections.

An alternative is to use `vroom::vroom_fwf()`, which does support this.

``` r
vroom::vroom_fwf(pipe("gecho -e 'a b\nc d'"), vroom::fwf_widths(c(2, 1)))
#> # A tibble: 2 x 2
#>   X1    X2   
#>   <chr> <chr>
#> 1 a     b    
#> 2 c     d
```

<sup>Created on 2020-09-14 by the [reprex package](https://reprex.tidyverse.org) (v0.3.0)</sup>

**Comment by jimhester** [comment]
Fixed by https://github.com/tidyverse/readr/pull/1172
