### ISSUE TITLE
Unexpected handling of multiple input files in readr::read_lines

### ISSUE THREAD

**Issue by aetiologicCanada** [tidyverse/readr#1006]
I am attempting to get readr::read_lines to read in multiple files. 
Works fine for one file, but when filepath is a vector n>1, it does not return the contents of all of the files. 

---

Brief description of the problem

```r
library(tidyverse)

text1 = "12345"
text2 = "abcde"

# read a single file
#
file1 = "file1.csv"
file2 = "file2.csv"

write(text1, file1)
write(text2, file2)
bothfiles=c(file1, file2)


#works fine
readr::read_lines(file=file1)
#works fine
readr::read_lines(file=file2)

#now try to read both ..
readr::read_lines(file=bothfiles)
# fails

# Expected result:
# "12345"
# "abcde"

# This fails also
map_df(bothfiles, readr::read_lines)

sessionInfo()
```
I suspect user error, of course, but seems worth documenting.

**Comment by cderv** [comment]
I see several things here. 

* I don't think `readr` functions are vectorized over files. So you can pass a vector of file paths as first argument. 

* using `purrr` is a good idea, but here `purrr::map_df` is not a good choice. To use `map_df`, the result of the function must be a data.frame (or tibble) so that it can be rbind. Here you need to use `map` and get a list or the correct `map_*` variant corresponding to the function result type.  here `map_chr` in your example

``` r
library(readr)

text1 = "12345"
text2 = "abcde"

file1 = fs::path_temp("file1.csv")
file2 = fs::path_temp("file2.csv")

readr::write_lines(text1, file1)
readr::write_lines(text2, file2)
bothfiles=c(file1, file2)


#works fine
readr::read_lines(file=file1)
#> [1] "12345"
#works fine
readr::read_lines(file=file2)
#> [1] "abcde"

# readr functions are not vectorize over files
# that is why it does not work
readr::read_lines(file=bothfiles)
#> [1] "C:/Users/chris/AppData/Local/Temp/RtmpIpLFLz/file1.csv"
#> [2] "C:/Users/chris/AppData/Local/Temp/RtmpIpLFLz/file2.csv"

# fails because result of read_lines is not a data.frame
purrr::map_df(bothfiles, readr::read_lines)
#> Error: Argument 1 must have names

# using map work
purrr::map(bothfiles, readr::read_lines)
#> [[1]]
#> [1] "12345"
#> 
#> [[2]]
#> [1] "abcde"

# using map_chr works also because result of read_lines is a character
purrr::map_chr(bothfiles, readr::read_lines)
#> [1] "12345" "abcde"
```

<sup>Created on 2019-07-03 by the [reprex package](https://reprex.tidyverse.org) (v0.3.0.9000)</sup>

As `read_lines` can handle vectors of character and read from them, useful for example. This is what is happening here with `bothfiles`. There is mention of that in the doc

> Literal data is most useful for examples and tests. It must contain at least one new line to be recognised as data (instead of a path) or be a vector of greater than length 1.

Hope it helps.

**Comment by jimhester** [comment]
Thanks for answering @cderv!
