### ISSUE TITLE
Partial reading from gzipped files

### ISSUE THREAD

**Issue by Shians** [tidyverse/readr#1096]
Using readr 1.3.1, if I wanted to read just a few lines from a gzipped table, I find myself waiting quite a long time to get results.

```{r}
library(readr)

df <- data.frame(
    x = 1:1e7,
    y = 1:1e7
)

temp_file <- paste0(tempfile(), ".gz")

write_tsv(df, temp_file)

# Almost instant
system.time(
    read.table(temp_file, nrows = 10, header = TRUE)    
)

# Takes a few seconds
system.time(
    read_tsv(temp_file, n_max = 10)
)
```

I think this is readr fully decompressing the gzipped file, whereas the read.table is streaming the decompression.

**Comment by jimhester** [comment]
Yes, this is correct. It won't be fixed in readr until the reading switches to use [vroom](https://vroom.r-lib.org/) as a backend.

If you want the behavior of `read.table()` with the API of readr for this use case in the meantime you could use `vroom::vroom(temp_file, n_max = 10)` and it will do what you describe.

As this is a known issue with readr #610  I am going to close this particular issue.
