### ISSUE TITLE
read_delim() calls tibble::data_frame()

### ISSUE THREAD

**Issue by greg-minshall** [tidyverse/readr#1099]
exactly in the case where the input file is empty, `read_delimited()` calls `tibble::data_frame()`, which causes a "life cycle" deprecated message.

in the example, assume "foo.csv" is an empty (zero-length) file.
```r
> require(readr)
Loading required package: readr
> read_csv("foo.csv")
# A tibble: 0 x 0
Warning message:
`data_frame()` is deprecated as of tibble 1.1.0.
Please use `tibble()` instead.
This warning is displayed once every 8 hours.
Call `lifecycle::last_warnings()` to see where this warning was generated.
```

**Comment by brianrice2** [comment]
Happy to propose a PR if someone's not already working on it&mdash;it seems as simple as changing to use `tibble::tibble()` instead of `tibble::data_frame()`. The [return value documentation](https://github.com/tidyverse/readr/blob/1fc4137f8c10ee37751b69f9b17ac4735cddc0e3/R/read_delim.R#L67-L68) and [news](https://github.com/tidyverse/readr/blob/f6857b55e56cd8875df4de02a860d9b3579df2f4/NEWS.md) says it returns a tibble, but an [empty data connection](https://github.com/tidyverse/readr/blob/1fc4137f8c10ee37751b69f9b17ac4735cddc0e3/R/read_delim.R#L191-L201) uses `tibble::data_frame()`. It looks like this is the only remaining use of `data_frame()` in the repo since this fix came just a few months before the deprecation message.
