### ISSUE TITLE
Feature request: specify manually True/False values accepted in col_logical()

### ISSUE THREAD

**Issue by JeremyPasco** [tidyverse/readr#1163]
Hi,
I often have to import tabular data with logical columns that have been filled with "Yes"/"No" strings or equivalents. For now I can't see a direct way to import these ones as logical values so I do this :

```r
library(tidyverse)
data <- read_csv("my_file.csv", col_types = cols(
  var1 = col_factor(levels = c("Yes", "No")),
  var2 = col_factor(levels = c("OK", "KO")),
)) %>%
  mutate(
    var1 = var1 == "Yes",
    var2 = var2 == "OK"
  )
```

By default accepted true/false values for col_logical are only: 1/0/T/F/TRUE/FALSE. Would it be possible to change them with arguments in a more direct approach like this one?

```r
library(tidyverse)
data <- read_csv("my_file.csv", col_types = cols(
  var1 = col_boolean(true_values = "Yes", false_values = "No"),
  var2 = col_boolean(true_values = "OK", false_values = "KO"),
))
```

With ideally the possibility to put vectors in true_values and false_values, allowing something like:
```r
col_boolean(true_values = c("Yes", "OK"), false_values = c("No", "KO"))
```

**Comment by msberends** [comment]
Not sure if this is something for readr, but I’ll leave that for the developers. In the meanwhile, you might like cleaner, that contains a `clean_logical()` function: https://msberends.github.io/cleaner/reference/clean.html. 

If you define the true and false parameters yourself, they will be interpreted as regular expressions:

```r
clean_logical(x = c("Positive", "Negative", "Unknown", "Unknown"),
              true = "pos",
              false = "neg")
#> [1]  TRUE FALSE    NA    NA

clean_logical(x = c("Probable", "Not probable"),
              true = ".*",
              false = "not")
#> [1]  TRUE FALSE
```

**Comment by jimhester** [comment]
Thanks for filing this issue! While I agree this might be a nice feature, it would take a bit of work to implement and because there are fairly straightforward workarounds I think it better not to implement it. For now I think we will stick with the current behavior.

Developing good software requires relentless focus, which means that we have to say no to many good ideas.

Even though we're closing this issue, we really appreciate the feedback, and hope you'll continue to contribute in the future :smile:
