### ISSUE TITLE
Documentation Request: Improved Callback Documentation

### ISSUE THREAD

**Issue by billdenney** [tidyverse/readr#1165]
Related to #510 and #1164, I was trying to write my own chunked callback, but it takes forever, so I think that I'm doing something wrong.  Can you provide a pointer to documentation (or write new documentation) of each of the methods for the callback functions to help understand how to write them more efficiently?

(I realize that this isn't a full reprex since `file_positions` is undefined.  To me, the paragraph above describes the issue and the info below just shows my incorrect attempt.  Given that the overall issue is that it takes too long to run, a "minimal" example is hard to make.  If desired, I can, though.)

```r
library(readr)
read_fwf_chunked <- function(file,
                             chunk_size=10000,
                             skip=0,
                             progress=show_progress(),
                             ...) {
  callback_fun <- function(data, index) {
    lapply(
      X=data,
      FUN=read_fwf,
      ...
    )
  }
  callback <- DataFrameCallback$new(callback_fun)
  ret <-
    read_lines_raw_chunked(
      file=file,
      callback=callback_fun,
      chunk_size=chunk_size,
      skip=skip,
      progress=progress
    )
  ret
}

d_raw <-
  read_fwf_chunked(
    file="ftp://ftp.cdc.gov/pub/Health_Statistics/NCHS/Datasets/DVS/natality/Nat2019us.zip",
    col_positions=file_positions,
    chunk_size=10000
  )
```

**Comment by jimhester** [comment]
readr actually cannot read a zip file from an external source, that it attempts to do so without error here seems to be a bug. Additionally even if this would work the code you posted is going to be very slow because reading from an external connection causes readr put the entire file in memory as does extracting from a zip file, so you will have the data in memory potentially 3 times. Downloading and extracting the file first will likely use far less memory.

Have you tried using [vroom::vroom_fwf()](https://vroom.r-lib.org/reference/vroom_fwf.html) for this file, it reads it pretty quickly, even if you don't use altrep.

```r
system.time(x <- vroom::vroom_fwf("~/p/readr/Nat2019PublicUS.c20200506.r20200915.txt", altrep = FALSE))

#   user  system elapsed
# 28.708   2.095  19.205
```

**Comment by hadley** [comment]
I don’t think these functions are terribly important so I don’t have a problem with leaving them as is (or keyword internal-ing  them) so fewer people come across them.

**Comment by jimhester** [comment]
They actually have always been keyword internal.

**Comment by jimhester** [comment]
But they are also in the pkgdown index, so they show up on the site, which I guess is how people are discovering them. Perhaps we should omit them there.

**Comment by hadley** [comment]
Yeah, I think so.

**Comment by jimhester** [comment]
I removed them from the pkgdown index in 696ddc2665d, so will close this issue.
