### ISSUE TITLE
read_csv column read as numeric loses accuracy for some numbers

### ISSUE THREAD

**Issue by M3IT** [tidyverse/readr#1188]
Some numbers (e.g. 0.66) read as numeric aren't imported precisely.
Specifying double seems to fix the problem, but shouldn't numeric have the same result?

``` r
library(readr)
library(tibble)

test_source <- tribble(
  ~num, ~dbl,
  0.65,   0.65,
  0.66,   0.66,
)

write_csv(test_source, 'test.csv')

test <- read_csv('test.csv', col_types = 'nd')

# Note addtional zero at end of numeric 0.66
test
#> # A tibble: 2 x 2
#>     num   dbl
#>   <dbl> <dbl>
#> 1 0.65   0.65
#> 2 0.660  0.66

# Works as expected for 0.65
test$num[1] == 0.65
#> [1] TRUE
test$dbl[1] == 0.65
#> [1] TRUE

# Works as expected for 0.66 read as double
test$dbl[2] == 0.66
#> [1] TRUE
test$dbl[2] - 0.66
#> [1] 0

# Unexpected result for 0.66 read as numeric
test$num[2] == 0.66
#> [1] FALSE
test$num[2] - 0.66
#> [1] -1.110223e-16
```

<sup>Created on 2021-04-03 by the [reprex package](https://reprex.tidyverse.org) (v1.0.0)</sup>

**Comment by jimhester** [comment]
Ultimately this is due to [R FAQ - 7.3.1 - Why doesn't R think these two numbers are equal](https://cran.r-project.org/doc/FAQ/R-FAQ.html#Why-doesn_0027t-R-think-these-numbers-are-equal_003f). `0.66` cannot be represented exactly with IEEE 754 binary64 numbers. The algorithms used to parse the numbers is different and as a result the least significant bit differs in this case, it is a 1 for the double parser and a 0 for the numeric parser.

``` r
library(readr)
library(tibble)

test_source <- tribble(
  ~num, ~dbl,
  0.65,   0.65,
  0.66,   0.66,
)

write_csv(test_source, 'test.csv')

test <- read_csv('test.csv', col_types = 'nd')

test
#> # A tibble: 2 x 2
#>     num   dbl
#>   <dbl> <dbl>
#> 1 0.65   0.65
#> 2 0.660  0.66

pryr::bits(test$dbl[[2]])
#> Registered S3 method overwritten by 'pryr':
#>   method      from
#>   print.bytes Rcpp
#> [1] "00111111 11100101 00011110 10111000 01010001 11101011 10000101 00011111"
pryr::bits(test$num[[2]])
#> [1] "00111111 11100101 00011110 10111000 01010001 11101011 10000101 00011110"
```

<sup>Created on 2021-04-05 by the [reprex package](https://reprex.tidyverse.org) (v1.0.0)</sup>

I don't think there is anything wrong with the parsers, this is just due to rounding and you should not rely on exact equivalence when comparing any floating point number.
