### ISSUE TITLE
Recolor red text in messages

### ISSUE THREAD

**Issue by garrettgman** [tidyverse/readr#1285]
**Can we change the readr messages to avoid red text?** I encounter students who see the red text and assume it is an error message. They panic or begin troubleshooting and cease to make progress. This happens frequently.

<img width="407" alt="Screen Shot 2021-08-23 at 9 57 49 AM" src="https://user-images.githubusercontent.com/85014/130470873-3ee67812-6398-4f87-892e-8cf73ea26285.png">

The student shouldn't jump to the wrong conclusion, but it is probably not helpful to blame them. I can compensate by over-teaching what is happening for my students, but that won't help everyone.

**readr will be more welcoming for some new R users if we save red text for warnings and error messages.** 

```
# (No reprex because this is a human factors problem)
```

**Comment by jimhester** [comment]
All readr versions after 1.4.0 (released on 2020-10-05) avoided the output of red text, by using `rlang::inform()` rather than `message()`. It seems you or your users must be using an older version of readr for some reason.

Though I should mention that it is red not because of anything readr is actively doing, but because RStudio outputs any message on stderr as red, https://github.com/rstudio/rstudio/issues/2574.

**Comment by garrettgman** [comment]
Thanks @jimhester!
