### ISSUE TITLE
Bug in read_delim  with scientific notation

### ISSUE THREAD

**Issue by ShinyFabio** [tidyverse/readr#1325]
I've a bunch of txt file with some values in scientific notation that I read with `read_delim()`. I had a problem with just one text file that has an "0,000E0" as a value. The function doesn't convert that value to 0 and so the column becomes a character column. The funny thing is that if you run `parse_number("0,000E00")` it returns correctly 0.
That's the file where I have the problem.
[AF-T141_LPS4h_2_nonlabeled.txt](https://github.com/tidyverse/readr/files/7522512/AF-T141_LPS4h_2_nonlabeled.txt)
 
And that's the function that I use to read it:
`readr::read_delim(x, "\t", escape_double = FALSE, trim_ws = TRUE, skip = 5)`

The problem is with the "Area" column as you can see.

**Comment by sbearrows** [comment]
What happens if you specify the column types? Right now the parser that readr is actually using is `parse_guess()` since you aren't supplying it with column types. When I ask readr to guess I get...

``` r
readr::guess_parser("0,000E00")
#> [1] "character"
```

<sup>Created on 2022-04-08 by the [reprex package](https://reprex.tidyverse.org) (v2.0.1.9000)</sup>

which matches what you're seeing. I would try supplying a more extensive column specification. For example:

``` r
library(readr)
t <- tempfile(fileext = ".txt")

df <- tibble::tibble(x = c("0,000E00", "3,452E3"),
                     y = c(1.2, 2.2))

write_delim(df, t)

read_delim(
  t,
  col_types = cols(x = col_number(),
                   y = col_double())
  )
#> # A tibble: 2 × 2
#>         x     y
#>     <dbl> <dbl>
#> 1       0   1.2
#> 2 3452000   2.2
```

<sup>Created on 2022-04-08 by the [reprex package](https://reprex.tidyverse.org) (v2.0.1.9000)</sup>

I noticed some numbers in your file like this `2.345.333,020` that look like they are using "," as decimal marks. If so, you'll need to specify the decimal mark with the `locale` option since that will change how readr parses columns. This might also explain why readr isn't guessing correctly. But it's better practice to specify column types than having readr guess, since it's not always perfect!

**Comment by jennybc** [comment]
To elaborate a bit more on this observation:

> I noticed some numbers in your file like this 2.345.333,020 that look like they are using "," as decimal marks. If so, you'll need to specify the decimal mark with the locale option since that will change how readr parses columns. This might also explain why readr isn't guessing correctly.

I think this is the key point. Yes it's true that it's always safest to specify column types. But in this particular case, by telling readr (vroom, really, in this case) about the decimal and grouping mark, you regain access to column type guessing.

``` r
library(readr)

guess_parser("0,000E00", locale = locale(decimal_mark = ","))
#> [1] "double"

inline_input <- glue::glue('
 x y
 0,000E00 1.2
 3,452E3 2.2
 2.345.333,020 3.3')

read_delim(inline_input)
#> Rows: 3 Columns: 2
#> ── Column specification ────────────────────────────────────────────────────────
#> Delimiter: " "
#> chr (1): x
#> dbl (1): y
#> 
#> ℹ Use `spec()` to retrieve the full column specification for this data.
#> ℹ Specify the column types or set `show_col_types = FALSE` to quiet this message.
#> # A tibble: 3 × 2
#>   x                 y
#>   <chr>         <dbl>
#> 1 0,000E00        1.2
#> 2 3,452E3         2.2
#> 3 2.345.333,020   3.3

read_delim(
  inline_input,
  locale = locale(decimal_mark = ",", grouping_mark = ".")
)
#> Rows: 3 Columns: 2
#> ── Column specification ────────────────────────────────────────────────────────
#> Delimiter: " "
#> num (2): x, y
#> 
#> ℹ Use `spec()` to retrieve the full column specification for this data.
#> ℹ Specify the column types or set `show_col_types = FALSE` to quiet this message.
#> # A tibble: 3 × 2
#>          x     y
#>      <dbl> <dbl>
#> 1       0     12
#> 2    3452     22
#> 3 2345333.    33
```

<sup>Created on 2022-04-12 by the [reprex package](https://reprex.tidyverse.org) (v2.0.1.9000)</sup>

**Comment by ShinyFabio** [comment]
I didn't want to specify the column type by myself because the files are generated by a software and I don't know if one day they decide to change the column names or add more columns. Since I didn't received a quick answer I used the `readr::parse_number(Area)` in combination with `dplyr::mutate` if that column is a character, but your solution is much more elegant and compact. Thank you! I didn't think about the decimal mark. But now I have a question, why `parse_number()` correctly identifies the column type even if I don't provide the decimal mark? Maybe a different default option?

**Comment by sbearrows** [comment]
Getting warnings if your column names change is helpful since your analysis later on in your pipeline will fail and getting warnings early on makes it easier to debug. For those reasons, we usually recommend providing column specification by name.

The default option for decimal marks is “.” so some of your columns may be parsed correctly. But if your file uses booth “,” and “.” as decimal marks, then I have doubts that all your columns are being parsed correctly.

It’s dangerous to have a file using both of these decimal marks. For example, if column `x` and column `y` are using different decimal marks but are both being parsed as numbers, your values may be off by several orders of magnitude, depending on how you parse the file:

``` r
library(readr)

inline_input <- glue::glue('
 x y
 0,000E00 1.234
 3,452E2 2.248')

# using the default decimal mark

read_delim(
  inline_input,
  col_types = cols(
    x = col_number(),
    y = col_double()
  ),
  show_col_types = FALSE
)
#> # A tibble: 2 × 2
#>        x     y
#>    <dbl> <dbl>
#> 1      0  1.23
#> 2 345200  2.25

# specify a decimal mark for the entire file

read_delim(
  inline_input,
  locale = locale(decimal_mark = ",", grouping_mark = "."),
  show_col_types = FALSE
)
#> # A tibble: 2 × 2
#>       x     y
#>   <dbl> <dbl>
#> 1    0   1234
#> 2  345.  2248
```

<sup>Created on 2022-04-14 by the [reprex package](https://reprex.tidyverse.org) (v2.0.1.9000)</sup>

I’d recommend you first scrutinize the software you are using to make sure there isn’t a solution there. If there isn’t, than I’d actually recommend bringing in all your columns as characters and then parsing them to numeric depending on which decimal marks the columns are using:

``` r
library(readr)
library(dplyr)
#> 
#> Attaching package: 'dplyr'
#> The following objects are masked from 'package:stats':
#> 
#>     filter, lag
#> The following objects are masked from 'package:base':
#> 
#>     intersect, setdiff, setequal, union


inline_input <- glue::glue('
 x y
 0,000E00 1.234
 3,452E2 2.248')


output <- read_delim(
  inline_input,
  col_types = cols(
    x = col_character(),
    y = col_character()
  ),
  show_col_types = FALSE
)

# x uses "," and y uses "."
# since y uses "." (which is the default option) we don't have to specify it

output %>% mutate(
  x = parse_double(x, locale = locale(decimal_mark = ",", grouping_mark = ".")),
  y = parse_double(y)
)
#> # A tibble: 2 × 2
#>       x     y
#>   <dbl> <dbl>
#> 1    0   1.23
#> 2  345.  2.25
```

<sup>Created on 2022-04-14 by the [reprex package](https://reprex.tidyverse.org) (v2.0.1.9000)</sup>

**Comment by ShinyFabio** [comment]
Thank you very much for your help! I've just one question, since the problem is only with one column, is it possibile to specify the `col_types` for just that column or do I have to specify all? Because there are ~15 other columns that are guessed correctly.

**Comment by sbearrows** [comment]
Here is one way:

``` r
inline_input <- glue::glue("
 x y z
 0,000E00 1.234 5.67
 3,452E2 2.248 42.33")

# set the default column spec for the other column
# if you trust the column guessing you could also use .default = col_guess()
output <- read_delim(
  inline_input,
  col_types = cols(
    x = col_character(),
    .default = col_double()
  ),
  show_col_types = FALSE
)

# x uses "," as decimal mark
output %>% mutate(
  x = parse_double(x, locale = locale(decimal_mark = ",", grouping_mark = "."))
)
#> # A tibble: 2 × 3
#>       x     y     z
#>   <dbl> <dbl> <dbl>
#> 1    0   1.23  5.67
#> 2  345.  2.25 42.3
```

<sup>Created on 2022-05-03 by the [reprex package](https://reprex.tidyverse.org) (v2.0.1.9000)</sup>
