### ISSUE TITLE
type_convert parses commas out of character numbers

### ISSUE THREAD

**Issue by cloversleaves** [tidyverse/readr#1349]
Is this expected that `type_convert` will force the "choices" column below to be a number for those choices with commas?
Thank you@

```r
name <- c("Jon", "Bill", "Maria", "Ben", "Tina", "Vic", "Tab")
choices <- c("23", "41", "32", "58", "26", "2,3", "24,5")
singlechoice <- c(8, 52, 41, 99, 1, 4, 5)
df <- data.frame(name, choices, singlechoice)

str(df)
'data.frame':	7 obs. of  3 variables:
 $ name        : chr  "Jon" "Bill" "Maria" "Ben" ...
 $ choices     : chr  "23" "41" "32" "58" ...
 $ singlechoice: num  8 52 41 99 1 4 5


tdf <- type_convert(df)
str(tdf)   
'data.frame':	7 obs. of  3 variables:
 $ name        : chr  "Jon" "Bill" "Maria" "Ben" ...
 $ choices     : num  23 41 32 58 26 23 245
 $ singlechoice: num  8 52 41 99 1 4 5


```

**Comment by jennybc** [comment]
Yes I'd say this is expected behaviour. If you don't specify how to parse the data, readr has to guess. For the input `c("2,3", "24,5")`, the guess is "number".

So `parse_number()` is the actual parser used.

Then, for `parse_number()` we have that:

> The grouping mark specified by the locale is ignored inside the number.

https://readr.tidyverse.org/reference/parse_number.html

In the default locale, this grouping mark is the comma `,`. So that's why the commas are ignored. This is because the expected input is really a number like `1,234`.

``` r
library(readr)

guess_parser(c("2,3", "24,5"))
#> [1] "number"

parse_number(c("2,3", "24,5"))
#> [1]  23 245

default_locale()$grouping_mark
#> [1] ","

parse_number("1,234")
#> [1] 1234
```

<sup>Created on 2022-01-26 by the [reprex package](https://reprex.tidyverse.org) (v2.0.1.9000)</sup>

If you want that column to come in as character, then you'll need to say so.

``` r
library(tidyverse)

name <- c("Jon", "Bill", "Maria")
choices <- c("26", "2,3", "24,5")
singlechoice <- c(8, 52, 41)
(dat <- tibble(name, choices, singlechoice))
#> # A tibble: 3 × 3
#>   name  choices singlechoice
#>   <chr> <chr>          <dbl>
#> 1 Jon   26                 8
#> 2 Bill  2,3               52
#> 3 Maria 24,5              41
type_convert(dat, col_types = cols(choices = col_character()))
#> # A tibble: 3 × 3
#>   name  choices singlechoice
#>   <chr> <chr>          <dbl>
#> 1 Jon   26                 8
#> 2 Bill  2,3               52
#> 3 Maria 24,5              41
```

This has reduced to a very strange usage of `type_convert()` now, because now it's no longer doing any conversion at all. `type_convert()` is really intended to work on a data frame of character columns that are yet-to-be-parsed.

**Comment by cloversleaves** [comment]
Thank you for the explanation!

My actual use was importing many data sets with sometimes hundreds of variables.  I brought them in as character as they needed some munging. 

As a parser ` parse_number()` seems it would be useful more interactively. 

I thought `type_convert()` would help me fly a little blindly, but cautiously. 

Maybe for `type_convert()` it would be useful to have an option for level of parsiness, a regex option in the parser code to switch 1,586 to 1586 or 333,589.00 to 333589.00, etc.—to convert only things that met a more stringent number format considering the grouping mark.

(Thank you again @Jennybc for your work!! I've learned a lot from your e-book/posts)

**Comment by jennybc** [comment]
I've watched readr from a distance for years and now I've inherited the maintainership of readr and vroom. And I maintain readxl and googlesheets4, which also ingest rectangular data.

I've come to the conclusion that there's a hard upper bound of how successful column-type-guessing can be and it's well below 100%. When it fails, everyone has an idea about how it could have worked better in their case. But the problem is, most of those modifications are fiddly to implement and often conflict with each other 😣

I think, when column type guessing fails, the best next step is to get to know your data better and provide more info. I realize that is not happy news, especially with hundreds of variables. And, I'm sure, there are still some improvements we could make.

Thanks for your kind words and this is just me thinking out loud. I think we need to set expectations better in this ecosystem of packages and this issue catches me while I'm thinking a lot about this.

**Comment by cloversleaves** [comment]
Thank you! I can understand that perspective: everyone wants it to work out of the box and perfectly _their_ way. 

Also, previously, I compared, a little, `type_convert()`, `type.convert()`, and `hablar::retype()`.  Their results and their various documentation were semi-interesting inasmuch as that kind of thing can be :). Overall, I think that their use/purpose is a bit different.

I think the similar names helped me think that `type_convert()` was somehow an easier-to-use or tidy version of `type.convert()`.  But when col information was changed, I didn't get any warnings or notes (that I've come to take for granted in the many tidyverse functions I use) so I assumed everything was converted OK (according to my biased notions)—that 24,5 was still 24,5. 

Now I belatedly realize `type_convert()` is really `readr_convert()` or `parse_convert()` and that one needs to be more aware of the parsing schema used by readr.

Anyway--thank you again!
