### ISSUE TITLE
Does `guess_encoding()` return encodings by highest to lowest confidence?

### ISSUE THREAD

**Issue by peterdesmet** [tidyverse/readr#1351]
It seems `guess_encoding()` returns a tibble with the guessed encodings **sorted from highest to lowest confidence**, but that behaviour is not documented.

https://github.com/tidyverse/readr/blob/980d70d90c497fceca1b48c3d7b682fc23aa48aa/R/encoding.R#L12

Does it indeed sort by confidence? Can one reasonable use the first row as the encoding with the highest confidence (assuming there are no equal confidence percentages)?

``` r
library(readr)
encodings <- guess_encoding("https://raw.githubusercontent.com/frictionlessdata/frictionless-r/main/inst/extdata/deployments.csv")

# Guessed encodings
encodings
#> # A tibble: 3 × 2
#>   encoding   confidence
#>   <chr>           <dbl>
#> 1 UTF-8            0.8 
#> 2 ISO-8859-1       0.59
#> 3 ISO-8859-2       0.26

# Encoding with the highest confidence?
encodings$encoding[[1]]
#> [1] "UTF-8"
```

<sup>Created on 2022-01-17 by the [reprex package](https://reprex.tidyverse.org) (v2.0.1)</sup>

**Comment by jennybc** [comment]
I did not know so I looked at the docs for [`guess_encoding()`](https://readr.tidyverse.org/reference/encoding.html), which says:

> Uses stringi::stri_enc_detect(): see the documentation there for caveats.

I looked at the docs for [`stringi::stri_enc_detect()`]() and see the return value is described like so:

> The guesses are ordered by decreasing confidence.

So, yes, `guess_encoding()` returns the encoding from highest to lowest confidence, because that is what `stringi::stri_enc_detect()` does.
