### ISSUE TITLE
Cannot use any of `write_delim` functions when assigning array to tibble

### ISSUE THREAD

**Issue by kalaschnik** [tidyverse/readr#1388]
I am in a project where I need to init an empty tibble, and I now the number of rows in advance; yet not the number of cols.

I am using helper functions for some column assignments, and they either return a single value (then I use vector recycling) or they return a vector (but the class of array) with the exact length of my tibble. However, it seems a class of array is toxic for the `write_delim` family, while `write.table` functions do indeed work fine.

## Steps Reproduce
```r
df <- tibble(.rows = 5)
df$ID <- as.array("01") # recycling on purpose
df$Country <- as.array(c("DE", "IT", "EN", "NZ", "NO"))
write_tsv(df, "wontwork.tsv")
```

Is that a bug? Or am I missing some R backstory on this?

**Comment by sbearrows** [comment]
It's failing because readr doesn't support writing columns with `dim` attributes (which includes arrays). Error messaging for this is a little broken right now for lists and matrices so we do have some work to do here (see https://github.com/tidyverse/readr/issues/1341) and I think from the error message it may not be clear that arrays are also forbidden. When I run your example I get the following:

``` r
t <- tempfile(fileext = ".tsv")
df <- tibble::tibble(.rows = 5)

df$ID <- as.array("01")
df$Country <- as.array(c("DE", "IT", "EN", "NZ", "NO"))

readr::write_tsv(df, t)
#> Error in `cli_block()` at readr/R/write.R:478:4:
#> ! `x` must not contain list or matrix columns:
#> x invalid columns at index(s): 1
#> 2

unlink(t)
```

<sup>Created on 2022-04-08 by the [reprex package](https://reprex.tidyverse.org) (v2.0.1.9000)</sup>

I'm not clear on why you need `as.array()` here but I'm assuming you have a specific usage for it that isn't easily expressed in a reprex because otherwise, your example works as expected using vectors:

``` r
t <- tempfile(fileext = ".tsv")
df <- tibble::tibble(.rows = 5)

# don't use as.array()
df$ID <- c("01")
df$Country <- c("DE", "IT", "EN", "NZ", "NO")

readr::write_tsv(df, t)

readr::read_tsv(t, show_col_types = FALSE)
#> # A tibble: 5 × 2
#>   ID    Country
#>   <chr> <chr>  
#> 1 01    DE     
#> 2 01    IT     
#> 3 01    EN     
#> 4 01    NZ     
#> 5 01    NO

unlink(t)
```

<sup>Created on 2022-04-08 by the [reprex package](https://reprex.tidyverse.org) (v2.0.1.9000)</sup>

I'd suggest that if you really need `as.array()` you could mutate your columns before trying to write:

``` r
t <- tempfile(fileext = ".tsv")
df <- tibble::tibble(.rows = 5)

df$ID <- as.array("01")
df$Country <- as.array(c("DE", "IT", "EN", "NZ", "NO"))

# mutate columns first
df <- dplyr::mutate_all(df, as.vector)

readr::write_tsv(df, t)

readr::read_tsv(t, show_col_types = FALSE)
#> # A tibble: 5 × 2
#>   ID    Country
#>   <chr> <chr>  
#> 1 01    DE     
#> 2 01    IT     
#> 3 01    EN     
#> 4 01    NZ     
#> 5 01    NO

unlink(t)
```

<sup>Created on 2022-04-08 by the [reprex package](https://reprex.tidyverse.org) (v2.0.1.9000)</sup>
