### ISSUE TITLE
Feature request: multi-line comments

### ISSUE THREAD

**Issue by japhir** [tidyverse/readr#1403]
All data on [pangaea](https://pangaea.org), an online database for geoscience data, has headers with metadata in the form of C# comments (I think?)

For a data file like this (real example on https://doi.pangaea.de/10.1594/PANGAEA.917500)

comment_syntax.tab
```
/* 
comment
more comment
*/
header1	theader2	header3
0.1	0.3	0.5
```

``` r
library(readr)
read_tsv("comment_syntax.tab", comment = "/*")
#> Warning: One or more parsing issues, see `problems()` for details
#> Rows: 5 Columns: 1
#> ── Column specification ────────────────────────────────────────────────────────
#> Delimiter: "\t"
#> chr (1): comment
#> 
#> ℹ Use `spec()` to retrieve the full column specification for this data.
#> ℹ Specify the column types or set `show_col_types = FALSE` to quiet this message.
#> # A tibble: 5 × 1
#>   comment                    
#>   <chr>                      
#> 1 "more comment"             
#> 2 "*/"                       
#> 3 "header1\theader2\theader3"
#> 4 "0.1"                      
#> 5 "0.5"
```

<sup>Created on 2022-05-19 by the [reprex package](https://reprex.tidyverse.org) (v2.0.1)</sup>

A multiline comment syntax would be nice!

Note that for pangaea, there is also a [pangaear](https://docs.ropensci.org/pangaear/) package available which reads in data as a list of datasets, which doesn't have this issue. The only problem there is that sometimes column names are duplicated and almost always have special characters and spaces, but that's a different issue.

**Comment by jennybc** [comment]
If the multi-line comments are always at the top as in the example above, you could use `skip` (possibly with some pre-work, if you want to detect how many rows to skip programatically).

But I'm afraid otherwise, no, readr / vroom is not going to gain support for multi-line comments. It runs fairly counter to the parsing strategy, so the added complexity is not justified by how infrequent this phenomenon is in general (although I understand it may be common for you).

You might want to search the readr and vroom issues for "pipe". The previous maintainer (jimhester, without the `@`, so as not to notify him) has showed some good examples over the years of pre-processing data with command line tools, before parsing with readr (or vroom). You might be able to do something similar. Examples: #1157, #1003,

**Comment by japhir** [comment]
Thank you for your elaborate reply! I understand why/how it's out of scope, I was looking at the C++ source code and as far as I understood it it's a line-by-line parser.
I have successfully used the `skip = 73` a couple of times, but indeed this requires you to look at how many lines are comments in the raw data prior to reading it in. Perhaps I could have looked for the final `*/` line, gotten that line number and then passed that to the skip argument. For now I'll just use the pangaear package :).

**Comment by jennybc** [comment]
> line-by-line parser

Multiple threads can be indexing different "chunks" of the file and you can't guarantee where those boundaries fall relative to multi-line comments. And if the multi-line comments only happen at the very top, then it's much more practical to determine how many lines to `skip`.

**Comment by jennybc** [comment]
> And if the multi-line comments only happen at the very top, then it's much more practical to determine how many lines to `skip`.

This is, in fact, exactly what pangaear is doing:

https://github.com/ropensci/pangaear/blob/851eb817ee40f80add2cdd25262d585ee49fc23a/R/zzz.R#L23-L31
