### ISSUE TITLE
`parse_number` cannot handle "-" in the string

### ISSUE THREAD

**Issue by albert-ying** [tidyverse/readr#1428]
Brief description of the problem

```r
parse_number("xx-xx: 898")
```

I expect to get `898` but instead, I got:

```r
Warning: 1 parsing failure.
row col expected     actual
  1  -- a number xx-xx: 898

[1] NA
attr(,"problems")
# A tibble: 1 × 4
    row   col expected actual    
  <int> <int> <chr>    <chr>     
1     1    NA a number xx-xx: 898
```

**Comment by sbearrows** [comment]
Looks like the dash is being recognized as a negative sign so I think this is expected behavior. Here is where this parsing is happening for `parse_number` in readr https://github.com/tidyverse/readr/blob/5cac6ed921f401293fe7229acaa18d02464f42a8/src/QiParsers.h#L254-L266
Unfortunately, parsing isn't always exact and in some cases fails to parse. I'd suggest stripping the `-` and then parsing.

``` r
my_num <- gsub("xx-xx: 898", pattern = "-", replacement = "")
parse_number(my_num)
#> [1] 898
```

**Comment by dwinsemius** [comment]
The suggested strippage should probably use a pattern like "-[^0-9]]

**Comment by dmurdoch** [comment]
@dwinsemius, your pattern has some issues too, e.g. with "-.5", or "1-a6".  This stuff can be tricky!
