### ISSUE TITLE
read_csv unnecessarily renames column when dots in column names

### ISSUE THREAD

**Issue by barryrowlingson** [tidyverse/readr#1512]
Given a CSV file with names like this - note the numeric part of the name is in order 2, 1, 3 here:
```
A...2, A...1, A...3
12345, 23456, 33333
```
Then `read_csv` renames columns, which seems unnecessary and may lead to misinterpretation of which column is actually `A...1`:

```r
> read_csv("test.csv")
New names:
• `A...2` -> `A...1`
• `A...1` -> `A...2`
...
```

This results in columns having the wrong names:

```r
# A tibble: 1 × 3
  A...1 A...2 A...3
  <dbl> <dbl> <dbl>
1 12345 23456 33333
```

Compare with `read.csv` which doesn't incorrectly rename the columns:

```r
> read.csv("test.csv")
  A...2 A...1 A...3
1 12345 23456 33333
```

One liner example:

```r
> read_csv("A...2,A...1,A...3\n1,2,3\n")
New names:
• `A...2` -> `A...1`
• `A...1` -> `A...2`
```

```r
> packageVersion("readr")
[1] ‘2.1.4’
```

**Comment by jennybc** [comment]
You've got an input where the existing names are perfectly crafted to clash with readr's default name repair strategy. If you want to use `readr::read_csv()` instead of `read.csv()`, then you will also need to specify a different name repair strategy for such input. For example, you could request "no repair" like so:

``` r
readr::read_csv("A...2,A...1,A...3\n1,2,3\n", name_repair = "minimal")
#> # A tibble: 1 × 3
#>   A...2 A...1 A...3
#>   <dbl> <dbl> <dbl>
#> 1     1     2     3
```

The name repair strategies used in readr and elsewhere are documented in [`vctrs::vec_as_names()`](https://vctrs.r-lib.org/reference/vec_as_names.html). readr's default is `"unique"`:

https://vctrs.r-lib.org/reference/vec_as_names.html#unique-names

> Pre-existing suffixes of the form `...j` are always stripped, prior to making names unique, i.e. reconstructing the suffixes. If this interacts poorly with your names, you should take control of name repair.

**Comment by barryrowlingson** [comment]
Although perfectly crafted here, Qualtrics' CSV export format uses column names of this form - eg Q23...19 - which get mangled up by default when read with `read_csv`. Now I can't ever trust the default behaviour, so why should I ever use it?
