### ISSUE TITLE
Think about how to extract colspec package

### ISSUE THREAD

**Issue by hadley** [tidyverse/readr#237]
for use in other data import packages

**Comment by hadley** [comment]
@jennybc do I remember that you worked on this?

**Comment by jennybc** [comment]
Well, I think we can say I "asked about / asked for" such a package.  Specifics that have come up in email (some answers from memory).

Q: Are `NA` variable names going to persist?  Is the "no munging of variable names" here to stay"?
A: No, and yes.

Q: Is it intentional that an all-`NA` column is `NA_character_` and not logical?
A: No, it should be logical.
*Sidebar: above applies to `readr`. `readxl` returns `NA_real_` in the same scenario.*

Q: Could `tidyr::spread()` use `readr::type_convert()` instead of base `type.convert()`?
A: That is the plan, but need to keep an eye on dependencies.

Q: Can we have a column conversion package?
A: Perhaps but it's hard.

Consistency around empty columns.

**Comment by hadley** [comment]
I think I got confused with your col range (?) package.

If we did do this, we might want to pull out the `select` helpers from dplyr since it's nice to be able to select sets of variables with them.
