### ISSUE TITLE
write_csv appends .0 to numbers

### ISSUE THREAD

**Issue by wdenton** [tidyverse/readr#526]
```
data.frame(x = c(1, 2)) %>% write_csv("test.csv")
```

Result:

```
x
1.0
2.0
```

Forcing x to integer prevents it but it seems surprising.

**Comment by josiekre** [comment]
This has also bitten me a couple times. It takes me a while to debug this problem in automated scripts as it is unexpected. Running the same code pre-v1.0 does not do this.

**Comment by hadley** [comment]
Why is that a problem?

**Comment by josiekre** [comment]
A lot of my scripts in R right out data to read into python for simulation etc. When the csv has a double rather than an int, it usually causes an error eventually. I myself am forced to type cast to int in R before writing now.

I guess the problem might be with my code earlier. Is there a reason I should not expect an int after computing a count variable with n() or row_number()?

**Comment by rdinter** [comment]
I also ran into this issue recently which affected a few of my "year" variables in a dataset and created problems merging that particular dataset with others.

`data.frame(x = c(1999, 2000, 2001)) %>% write_csv("test.csv")
`
Which gives me:

> x
> 1999.0
> 2e3
> 2001.0

This isn't a problem if the variable is classified as.integer() or as.character() and is probably good coding practice to do this anyway. But it feels like there was an update(?) to the readr package where previously the ".0" precision was not a part of the csv output of write_csv(). For comparison, the write.csv() function does not add in the ".0" precision either.

**Comment by chpmoreno** [comment]
I had the same issue related to years but also with some other factor variables. In particular, I used R for reading a SPSS file (.sav) and then writing a .csv that would be used for creating MySQL databases. The problem is that the MySQL schema my colleagues made didn't work properly with doubles because they are integers and were defined like this in the schema. Therefore, I create a script for detecting if each variable in the data frame generated after we read the SPSS file using foreign package (I tried to use haven but it doesn't read properly the NA assigned in the .sav) is a character, numeric or integer. I also had to deal with some indexes (like 00455). At the end the script worked but it is not the most efficient. It is something like this:

```
library(readr)
library(foreign)
library(stringi)

data <- read.spss("data.sav",
                to.data.frame = TRUE, use.value.labels = FALSE)

data_alter <- as.data.frame(seq(1, nrow(data)))
for(i in 1:ncol(data)) {
  if(sum(is.na(as.numeric(stri_replace_all_fixed(as.character(data[, i]), " ", "")))) == length(data[,i])){
    data_alter <- cbind(data_alter, as.data.frame(as.character(data[, i])))
  } else {
    if(all.equal(as.character(as.numeric(stri_replace_all_fixed(as.character(data[, i]), " ", ""))),
                 stri_replace_all_fixed(as.character(data[, i]), " ", "")) != TRUE){
      data_alter <- cbind(data_alter, as.data.frame(as.character(data[, i])))
    } else {
      if(all.equal(as.numeric(stri_replace_all_fixed(as.character(data[, i]), " ", "")), 
                   as.integer(as.numeric(stri_replace_all_fixed(as.character(data[, i]), " ", "")))) == TRUE){
        data_alter <- cbind(data_alter, as.data.frame(as.integer(data[, i])))
      } else {
        data_alter <- cbind(data_alter, as.data.frame(as.numeric(data[, i])))
      }
    }
    
  }
}
data_alter <- data_alter[, -1]
colnames(data_alter) <- colnames(data)
write_csv(data_alter, "data.csv", na = "")
```
Maybe in some way it would be useful if we could define some variables as integers.

**Comment by jennybc** [comment]
I just re-ran some 2015 scripts and this caused massive diffs in multiple csvs. I guess it doesn't really matter? But it would be nice if integer data still got written without the trailing `.0` for many of the reasons outlined above.

**Comment by hadley** [comment]
I think this behaviour will cause a little pain in the short term, but it reduces pain in the long-term by forcing you to be more explicit about column types.

It's straight-forward to convert all integerish columns yourself:

```R
library(purrr)

integerish <- function(x) x == trunc(x)
df %>% 
  map_if(~ all(integerish(.)), as.integer)
```

**Comment by hadley** [comment]
@jennybc integers are written out without trailing dots:

```R
data.frame(x = 1L) %>% format_csv()
#> [1] "x\n1\n"
```

**Comment by jennybc** [comment]
I think a year ago `write_csv()` would leave off the `.0` for individual numerics, if it was integer-ish. And if that applied to an entire variable, that made it look like integer in the csv, even though user did not properly make it integer.

Who knows ... my year-old scripts do a lot of other tidyverse processing in between `read_csv()` and `write_csv()`! *Something changed* (the data did not) but I have no burning need to know what.

<img width="264" alt="screen shot 2016-12-22 at 11 36 27 am" src="https://cloud.githubusercontent.com/assets/599454/21437841/fee2561e-c83a-11e6-836c-bd4e49b956d4.png">

**Comment by rgknight** [comment]
Another voice for returning to the old behavior. I've been caught by this many times.

If the tidyverse is not going to silently coerce from integer to double (https://github.com/hadley/vctrs/issues/7), it seems reasonable to make interger-ish values their integer representations when writing to file. Why be type strict on reading / writing integer vs double when we are not on manipulating integers?

For example, it's confusing to read an int var in, add zero to it, write_csv, then not be able to read the same file back in.

```
file <- "my_int_var\n0"

read_csv(file, col_types = "i") %>%
    mutate(my_int_var = my_int_var + 0) %>%
    write_csv("file.csv")

read_csv("file.csv", col_types = "i")

# you would need to add `as.integer(0)` to preserve type
```

My solution is to either stop reading integers, since they will likely be silently coerced to double at some point in my scripts anyway, or just go back to `write.csv`. 

Maybe `read_csv` should never guess integer, since "0" is not an integer in R? That wouldn't solve the problem mentioned earlier of sharing csvs with other programs.

**Comment by hadley** [comment]
Re-opening just to make sure we re-think this for the next release

**Comment by jimhester** [comment]
@rgknight You append `L` to a number to specify an integer, `0L` is used for integer 0.

I personally feel these types _need_ to be explicit, otherwise you can have a double column with 1000 "integers", that has doubles after the first 1000 and it will fail to parse.

**Comment by hadley** [comment]
Let's go back to the old behaviour. We're forcing people to care about the difference between integers and doubles, when that's not usually important in R.
