### ISSUE TITLE
Load from file delimited by multiple spaces?

### ISSUE THREAD

**Issue by javierluraschi** [tidyverse/readr#605]
For a file delimited by multiple spaces:

```
Column1    Column2    Column3
      A          1          X
      B          2          Y
```

Is it possible to load this table using only `readr`? If not, can we mark this one as a feature request?

I'm asking since users reported they were able to do this with `read.table`, but no longer with `readr` while using the data import wizard provided by RStudio.

**Comment by jimhester** [comment]
`readr::read_table()` is used to read whitespace delimited files.

``` r
f <- "Column1    Column2    Column3\n      A          1          X\n      B          2          Y\n"
cat(f)
#> Column1    Column2    Column3
#>       A          1          X
#>       B          2          Y
readr::read_table(f)
#> cols(
#>   Column1 = col_character(),
#>   Column2 = col_integer(),
#>   Column3 = col_character()
#> )
#> # A tibble: 2 × 3
#>   Column1 Column2 Column3
#>     <chr>   <int>   <chr>
#> 1       A       1       X
#> 2       B       2       Y
```

**Comment by hadley** [comment]
Note that the behaviour is subtly different between `read.table()` and `read_table()`: `read.table()` uses any sequence of whitespace as a delimiter, whereas `read_table()` assumes columns of whitespace in the same place.

If you want an exact match to `read.table()` we'd need to add something.

**Comment by javierluraschi** [comment]
I was honestly not aware of this functionality, I'll add it to the data import dialog. Thank you!

**Comment by kevinushey** [comment]
@javierluraschi: we _want_ to use the base R `read.table()` for this dialog, as we want to explicitly avoid a dependency on `readr` -- this is for the case where e.g. students or instructors are working in an environment where they cannot, or do not want, to install CRAN packages.

Lots of instructors relied on the old data import dialog using `utils::read.table()` so we definitely need to bring an analogue back that uses that.

**Comment by hadley** [comment]
If it's a functionality issue, we can definitely fix that in readr.

But you'll need a switch between readr and base R for `read.csv()` as well right? I think it would be a big step back to only allow import using base R.

**Comment by kevinushey** [comment]
We definitely want to allow both the base R readers and the `readr` family of readers (including e.g. `haven` and such) to co-exist; we just need to try and provide the old UI as well.

In other words, the ultimate goal is to just add back the import dialog `Import Data -> From Text File...` that older versions of RStudio had; I don't think we need to try to provide a single unified dialog that can farm out to either `read.table()` or `read_table()`.

**Comment by kevinushey** [comment]
Sorry, I came on far too negatively in my previous post. There really are two somewhat difficult to unify goals for the IDE here:

1. Add a dialog that interfaces with `read_table()`,
2. Bring back the old dialog that uses `read.table()` (for the aforementioned reasons)

We can probably add in the import dialog using `read_table()` (since I imagine that can reuse most of what we have) and then think about how we can logically make switching between `read.table()` / `read_table()` work naturally.

I do feel rather guilty about alienating a number of instructors who had e.g. built lecture materials around the use of RStudio's old data import dialog, so I hope we can find a compromise here.

**Comment by hadley** [comment]
Ok, we'll get an equivalent of `read.table()` into the next version of readr. 

I think we were accidentally too aggressive with the updated data import; it did shove tibbles and readr into peoples faces, rather than letting them upgrade to them when ready. (I think in the long run almost everyone will be better off with readr + tibbles, but it's not nice to force that on people)

**Comment by gregorgorjanc** [comment]
I would also vote for such a functionality in readr. While I understand that making additional columns for every instance of the delimiter makes sense, it is tricky when one gets a file with several spaces between columns and these multiple spaces are meant as a single delimiter. read.table() handles such cases gracefully. Are there any plans to accommodate such a situation in readr?

**Comment by gregorgorjanc** [comment]
Ah, I see read_table() solves all of this. Thanks!
