### ISSUE TITLE
printing dataframe CRASHES when variable contains a lot of text

### ISSUE THREAD

**Issue by randomgambit** [tidyverse/readr#682]
Hi,

I am reading a csv that contains a lot of news headlines. A sample row looks like this (I cannot post the data):

```

test
Out[8]: 
   Unnamed: 0         day                                                                                             HEADLINE
0           0  2013-01-01  American football- incredible win at Sun Bowl| this is the historic time - January...
```

Here the `HEADLINE` column can contain a lot of strings (actually, many many headlines concatenated together with a pipe). 

Problem is, when I read-in the data using `readr::read_csv`, even if the data is correctly imported, 

```
> news_agg <- read_csv('C://collapsed_news.csv',  n_max = 10)
Parsed with column specification:
cols(
  X1 = col_integer(),
  day = col_date(format = ""),
  HEADLINE = col_character()
)
```
typing `news_agg` to the console (to see the data) takes FOREVER. Actually Rstudio freezes and I have to kill it. What is going on here? Is the data incorrectly parsed for some reason?

Thanks!

**Comment by jimhester** [comment]
It is hard to say without having the actual data you are trying to print. However if the freeze only happens when you try to print the object this is almost assuredly not an issue with **readr**, rather it is an issue with the [tibble](https://github.com/tidyverse/tibble) package, which is use to print tibble objects (which is what the `read_xyz()` functions return).

**Comment by randomgambit** [comment]
hi @jimhester , yes you are right but I am not allowed to post the data. should I cross post in the tibble repo?

**Comment by jimhester** [comment]
Sure, however see if you can generate example data that mimics the behavior you describe. For instance what is the value of `nchar(out$HEADLINE[[1]])`, do you see the same behavior with random data of the same length?

Also FWIW you may want to reformat your data before reading into R, as it is not really usable in the current form without manipulation. 

Rather than
```
date1    headline1|headline2|headline3
date2    headline4|headline5
```

Try something like
```
date1    headline1
date1    headline2
date1    headline3
date2    headline4
date2    headline5
```

This way the data will be read in a format that is easily manipulated.
