### ISSUE TITLE
Warning message: In rbind(names(probs), probs_f) : number of columns of result

### ISSUE THREAD

**Issue by MatthieuStigler** [tidyverse/readr#685]
A warning message appears when reading a dataset with problems: *Warning message: In rbind(names(probs), probs_f) :  number of columns of result is not a multiple of vector length (arg 2)*. 

Try:

    y <- read_csv("x\n1\n2\nb", col_types = list(col_double()))

Is this warning a necessary warning, or resulting from coding error? It seems it does not appear with version 1.0.0?

**Comment by jzadra** [comment]
Since this is the top google result for this warning: I'm still getting this, and it is really unclear.  Not a result of *what* vector length?

**Comment by batpigandme** [comment]
@jzadra,
A different warning is now printed for the code that was above. It's hard to tell the _what_ without knowing the code that prompts the warning.

Could you please turn submit a self-contained [reprex](http://reprex.tidyverse.org/) (short for minimal **repr**oducible **ex**ample)? It will help us help you if we can be sure we're all working with/looking at the same stuff.

If you've never heard of a reprex before, you might want to start by reading the tidyverse.org [help page](https://www.tidyverse.org/help/).

**Comment by pconwell** [comment]
It seems to be related to readr setting the column type based on the first 1000 rows of the column. Here is a reproducible example:

```R
library(RCurl)
library(readr)

bad <- "https://raw.githubusercontent.com/pconwell/readr-test/master/test_bad.csv"
good <- "https://raw.githubusercontent.com/pconwell/readr-test/master/test_good.csv"

bad_url <- getURL(bad)
good_url <- getURL(good)

df.bad <- read.csv(textConnection(bad_url))
df.good <- read.csv(textConnection(good_url))

write.csv(df.bad, "bad.csv", row.names=F)
write.csv(df.good, "good.csv", row.names=F)

bad_csv <- read_csv("./bad.csv")
sapply(bad_csv, typeof)

good_csv <- read_csv("./good.csv")
sapply(good_csv, typeof)
```

As you can see, the 'good' df comes back with a type of character while the 'bad' df comes back with a type of double. The ONLY difference between the 'good' and 'bad' is the good list has 999 integer rows then 1 string row while the bad list has 1000 integer rows and then 1 string row.

It appears that readr is reading the first 1000 rows then assigning a type (in this case - double). The problem comes when somewhere further down the column you have a string. For example, I have a dataset with about 250,000 rows. The more recent entries are all formatted as integers but some of the older entries may have non-integer characters. (In other words, we used to track entries with something like Z1234 but now we track entries like 20180324055100 or something similar).

**Comment by xiangyum** [comment]
Thank you!  I ran into the same problem as OP. Changing the guess_max parameter did the trick.
