### ISSUE TITLE
Documentation for `read_delim` and its siblings still refers to the column-types vignette

### ISSUE THREAD

**Issue by Dulani** [tidyverse/readr#847]
The documentation for `read_delim` and its siblings still refers to the column-types vignette: `vignette(column-types).` In the closed issue #501, it says it was removed and included in the readr intro (so it probably should be removed from the documentation, right?).

**Comment by batpigandme** [comment]
Can you point out where you're finding this?
It's in the [documentation for `0.2.0` and `0.1.0`](https://github.com/tidyverse/readr/search?utf8=%E2%9C%93&q=column-types&type=), but the current version is `1.1.1`.

**Comment by batpigandme** [comment]
It looks like Jim removed this reference in https://github.com/tidyverse/readr/commit/3c69531d878b538782610e343fa1d3aebad0bded, but I do see what you mean in the CRAN PDF reference. Since it's been fixed in the code, I'm going to close this, but it will be reflected in the next release in the CRAN docs as well.
