### ISSUE TITLE
Unexpected error when reading directly from URL of compressed file

### ISSUE THREAD

**Issue by cboettig** [tidyverse/readr#891]
If I do: 

```r
readr::read_tsv("https://github.com/cboettig/taxald/releases/download/v1.0.0/data.2fitis_hierarchy.tsv.bz2")
```

I see the somewhat cryptic error: 

```r
Error in make.names(x) : invalid multibyte string 1
```

Using `download.file` on the URL first resolves this error.

 I'm guessing this is related to how readr guesses the file compression type?  Would it make sense for `readr` to check the file extension in this case, since a magic number isn't available?

**Comment by yutannihilation** [comment]
In the current implementation, when `file` is a URL, only `.gz` is checked and supported. 

https://github.com/tidyverse/readr/blob/05890c3b493458ad4699654ceed58d2515939e94/R/source.R#L122-L134

I guess this is because R provides `gzcon()` for gzip but doesn't for the other compression formats. Maybe readr should fall back to download file and read the file when the connection cannot be read directly?

**Comment by jimhester** [comment]
The error message you recieve in this case is now more informative.

```r
readr::read_tsv("https://github.com/cboettig/taxald/releases/download/v1.0.0/data.2fitis_hiera
  rchy.tsv.bz2")
#> Error: Reading from remote `bz2` compressed files is not supported,
#>   download the files locally first.
```
