### ISSUE TITLE
Auto-build website

### ISSUE THREAD

**Issue by hadley** [tidyverse/readr#916]
Using new pkgdown tools

**Comment by jimhester** [comment]
So this seems to be working now (https://readr.tidyverse.org/dev/) except for the logo not being found? Not sure if I have it in the wrong place or if it is a bug...

**Comment by jimhester** [comment]
Looks like @DavisVaughan's yardstick site has the same issue (https://tidymodels.github.io/yardstick/dev/), so maybe this is something that needs to be fixed in either pkgdown or the template packages.

**Comment by DavisVaughan** [comment]
I've been meaning to report that. Last time I checked, this was happening because `logo.png` was not being copied into the `dev` directory, and that is where `tidytemplate` was looking for it. But for the current `gh-pages` of `pkgdown`, the `logo.png` is both at the production level and the dev level, so maybe something changed and I need to try and rebuild the docs.

I find it interesting for `readr` that `logo.png` is in the production version but `logo.svg` is in the dev version?

**Comment by jimhester** [comment]
For the readr case this was fixed by deleting the svg logo https://github.com/tidyverse/readr/commit/317cd1f6726902d4a8e2634fc06a92f126361213

**Comment by hadley** [comment]
FWIW this was a bug in pkgdown which just got fixed
