### ISSUE TITLE
read_table2 parsing failure warning

### ISSUE THREAD

**Issue by dmitrienka** [tidyverse/readr#953]
```
> read_table2("1 x,y,z\n2 -x,-y,-z", col_names = c("A", "B"))
Warning: 1 parsing failure.
row col expected        actual         file
  2   B          embedded null literal data

# A tibble: 2 x 2
      A B       
  <dbl> <chr>   
1     1 x,y,z   
2     2 -x,-y,-z
```

**Comment by cderv** [comment]
I think you got the warning because you are missing an end of line on the second row. If you add a new line, it is fine.
``` r
readr::read_table2("1 x,y,z\n2 -x,-y,-z\n", col_names = c("A", "B"))
#> # A tibble: 2 x 2
#>       A B       
#>   <dbl> <chr>   
#> 1     1 x,y,z   
#> 2     2 -x,-y,-z
```

<sup>Created on 2019-01-06 by the [reprex package](https://reprex.tidyverse.org) (v0.2.1)</sup>

Warnings are made for user to know that something is not correct.
Sorry but I may have miss something. I don't see the issue about `readr` you want to report ? Can you elaborate on the [reprex](https://reprex.tidyverse.org/) ?
