### ISSUE TITLE
safer guessing on missing data?

### ISSUE THREAD

**Issue by cboettig** [tidyverse/readr#955]
I believe readr infers a literal NA in csv/tsv files as type logical, consistent with R's own behavior.  However, this seems to be asking for trouble when reading large tables with large amounts of missing data, where readr is frequently inclined to guess these columns as logicals and create coercion parsing errors.  Would it not be safer to default to the assumption that NA is a `as.character(NA)` instead of a logical NA?

**Comment by jennybc** [comment]
Some history:

  * Make an all-NA variable logical #662
  * read_csv column type guess for 1000 rows of "NA" is logical - should be character? #839
  * there's a 3rd conversation that I can't find 😔 but in my memory, it gets at this issue that you can upcast logical `NA` but it's much harder to downcast character `NA`, therefore it's better to assume `NA` until you have reason to do otherwise

**Comment by cboettig** [comment]
Thanks Jenny, these are excellent threads, sorry I didn't spot them 😊 .  I'm convinced!
