### ISSUE TITLE
file vs path argument to read_* and write_*

### ISSUE THREAD

**Issue by wolski** [tidyverse/readr#964]
I can not remember if `read_*`  or `write_*` requires the path argument, and which of those two needs file.
How about having the same argument name, either file or path, for read_ and write_?

**Comment by SamanthaToet** [comment]
I think of file and path as being the same since they point to the same connection.

Both `read.csv` and `write.csv` use the same term, file, in their documentation as does `read_csv`. Maybe updating the documentation for `write_csv` so that it uses the term file instead of path could help with confusion?

**Comment by wolski** [comment]
@SamanthaToet 
I am hoping for a different solution. read_ and write_ should have the same argument names as write. read. does. It would be `tidier` (this term is not my invention).

**Comment by brianrice2** [comment]
I submitted a PR changing write_csv to file instead of path, similar to how read_csv is already set up, based on these (kind of old) comments - if I am missing something feel free to let me know!
