### ISSUE TITLE
#lossing data when use read_csv to read the data

### ISSUE THREAD

**Issue by junqi108** [tidyverse/readr#995]
I used read_csv to read the data, however, I find some numeric data disappeared. I compared the results with the basic read.csv which still maintain the data. I feel maybe this is because my data contains many NAs. 
if needed, I can send my data files. 
```r

full.data.raw <-  
  read.csv(file.path(IntermediateResults, 'Squire_RDI_2001_2005_raw_data.csv'), header = T) 

#lossing data when use read_csv to read the data
full.data.raw.2 <-  
  read_csv(file.path(IntermediateResults, 'Squire_RDI_2001_2005_raw_data.csv')) 
  
full.data.raw %>% 
  select(leaf.area.vine) %>% 
  drop_na()

> result: 
> leaf.area.vine
> <dbl>
> 2579	9.70000000			
> 3054	7.95000000			
> 3055	8.66000000			
> 3056	10.63000000			
> 3083	8.63000000			
> 3084	9.62000000			
> 3085	10.85000000			
> 3086	6.40000000			
> 3087	10.59000000			
> 3088	10.72000000	

full.data.raw.2 %>% 
  select(leaf.area.vine) %>% 
  drop_na()

> result:
> 0 rows

```

**Comment by cderv** [comment]
Can you share some data to have a real [reprex](https://www.tidyverse.org/help/#reprex) ? 
This way we can try reproduce on our hand. 
And have you any message when parsing your file with readr ? 

Thanks !

**Comment by junqi108** [comment]
library(dplyr)
#> 
#> Attaching package: 'dplyr'
#> The following objects are masked from 'package:stats':
#> 
#>     filter, lag
#> The following objects are masked from 'package:base':
#> 
#>     intersect, setdiff, setequal, union
library(readr)
library(tidyr)

IntermediateResults ="K:\\Grape and Wine Research Programme\\SSIF 2017 advancing viticulture database\\Steve Green sap flow data\\Organized_data\\Squaires_RDI_2001_2005\\Squire_data_organization/Intermediate results"
full.data.raw <-
  read_csv(file.path(IntermediateResults, 'Squire_RDI_2001_2005_raw_data.csv'))
#> Parsed with column specification:
#> cols(
#>   .default = col_double(),
#>   season = col_character(),
#>   date = col_date(format = ""),
#>   treatment = col_character(),
#>   budburst.doy = col_logical(),
#>   flowering.doy = col_logical(),
#>   veraison.doy = col_logical(),
#>   Irrigation.mm.day = col_logical(),
#>   Irrigation.L.day = col_logical(),
#>   leaf.no.shoot.main = col_logical(),
#>   leaf.no.shoot.lateral = col_logical(),
#>   leaf.fw.shoot.main = col_logical(),
#>   leaf.fw.shoot.lateral = col_logical(),
#>   leaf.area.shoot.main = col_logical(),
#>   leaf.area.shoot.lateral = col_logical(),
#>   leaf.dw.shoot.main = col_logical(),
#>   leaf.dw.shoot.lateral = col_logical(),
#>   shoot.length.std.dev = col_logical(),
#>   shoot.length.std.error = col_logical(),
#>   leaf.area.shoot.std.dev = col_logical(),
#>   leaf.area.shoot.std.error = col_logical()
#>   # ... with 38 more columns
#> )
#> See spec(...) for full column specifications.
#> Warning: 4825 parsing failures.
#>  row  col expected  actual                                                                                                                                                                                                                                  file
#> 3340 sw.1 a double #DIV/0! 'K:\Grape and Wine Research Programme\SSIF 2017 advancing viticulture database\Steve Green sap flow data\Organized_data\Squaires_RDI_2001_2005\Squire_data_organization/Intermediate results/Squire_RDI_2001_2005_raw_data.csv'
#> 3340 sw.2 a double #DIV/0! 'K:\Grape and Wine Research Programme\SSIF 2017 advancing viticulture database\Steve Green sap flow data\Organized_data\Squaires_RDI_2001_2005\Squire_data_organization/Intermediate results/Squire_RDI_2001_2005_raw_data.csv'
#> 3340 sw.3 a double #DIV/0! 'K:\Grape and Wine Research Programme\SSIF 2017 advancing viticulture database\Steve Green sap flow data\Organized_data\Squaires_RDI_2001_2005\Squire_data_organization/Intermediate results/Squire_RDI_2001_2005_raw_data.csv'
#> 3340 sw.4 a double #DIV/0! 'K:\Grape and Wine Research Programme\SSIF 2017 advancing viticulture database\Steve Green sap flow data\Organized_data\Squaires_RDI_2001_2005\Squire_data_organization/Intermediate results/Squire_RDI_2001_2005_raw_data.csv'
#> 3340 sw.5 a double #DIV/0! 'K:\Grape and Wine Research Programme\SSIF 2017 advancing viticulture database\Steve Green sap flow data\Organized_data\Squaires_RDI_2001_2005\Squire_data_organization/Intermediate results/Squire_RDI_2001_2005_raw_data.csv'
#> .... .... ........ ....... .....................................................................................................................................................................................................................................
#> See problems(...) for more details.

full.data.raw %>% 
  select(ta) %>% 
  drop_na()
#> # A tibble: 0 x 1
#> # ... with 1 variable: ta <lgl>

**Comment by junqi108** [comment]
not sure whether this works

**Comment by cderv** [comment]
> #> Warning: 4825 parsing failures.
I think you need to check your file. There are some failures when parsing. Also, as you see in the spec, almost every column is parsed as logical. It does not seems right for your data based on your first example.
You need to check those failure, and the correct spec for `readr`. See the help
* [how to precise column spec](https://readr.tidyverse.org/articles/readr.html#column-specification)
* [How to use `problems()` for parsing failure](https://readr.tidyverse.org/articles/readr.html#rectangular-parsers)

From the warning message you get, it seems you have in a column with some double, others unexpected value in your file : `#DIV/0!`. It is a wild guess but is you csv file an export of an excel file ? `#DIV/0!` comes from |there](https://support.office.com/en-us/article/How-to-Correct-a-DIV-0-error-3a5a18a9-8d80-4ebb-a908-39e759a009a5) sometimes. You should look inside your csv file manually if possible.

Until the table is not parsed correctly, it will be difficult to conclude that there is a loss of data. A NA value is logical by default so if you column are parsed as logical, the result of `drop_na()` is correct
``` r
is.logical(NA)
#> [1] TRUE
library(magrittr)
tibble::tibble(ta = c(NA, NA)) %>%
  tidyr::drop_na()
#> # A tibble: 0 x 1
#> # ... with 1 variable: ta <lgl>
```

<sup>Created on 2019-04-30 by the [reprex package](https://reprex.tidyverse.org) (v0.2.1.9000)</sup>

`read.csv` seems to work because I think it will import everything as character so this does not happen but the parsing of the csv is no more correct (character instead of double)

> IntermediateResults ="K:\Grape and Wine Research Programme\SSIF 2017 advancing viticulture database\Steve Green sap flow data\Organized_data\Squaires_RDI_2001_2005\Squire_data_organization/Intermediate results"

Here, I can't reproduce because I don't have access to your file, or even a subset. You should ask your question to get some help on https://community.rstudio.com and follow the guide [FAQ: What's a reproducible example (`reprex`) and how do I do one?](https://community.rstudio.com/t/faq-whats-a-reproducible-example-reprex-and-how-do-i-do-one/5219)

Hope it helps.

**Comment by junqi108** [comment]
hi Christophe: thanks very much for the detail explanation. I understand it better now.  I often ignored the warnings.... i will have a detailed look of the parsing problem and how I can fix it. I did look at the reprex method, and try to use it. however, it seems problems with importing big dataset is a bit hard to reproduce. 
thanks again.
